version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - wordpress_db

  wordpress_db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfg_alberto
      MYSQL_USER: root
      MYSQL_PASSWORD: Sandia4you